#!/usr/bin/env bash

if [ -z "$1" ]
  then
    echo "Need path to conf file"; exit 1
fi

grunt &&
rm -rf html/ hotdoc-private/ sandbox/html/ &&
hotdoc --html-theme $PWD/dist run --conf-file $1 &&
mv html/ sandbox/ &&
rm -rf hotdoc-private &&
touch sandbox/trigger_refresh
